name: Build Pack

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    if: ${{ github.event.pull_request.title }} == "New Crowdin updates"
    strategy:
      matrix:
        gameVersion: [1.19]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Merge files
        run: |
          mkdir pack
          cp -R translated/zh_tw/source/zh_tw/${{ matrix.gameVersion }} pack
          cp -R meta/${{ matrix.gameVersion }} pack

      - name: compressed the resource pack to a zip file
        uses: vimtor/action-zip@v1
        with:
          files: pack
          dest: files/RPMTW-Translate-Resource-Pack-${{ matrix.gameVersion }}.zip
      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.gameVersion }}
          path: files/RPMTW-Translate-Resource-Pack-${{ matrix.gameVersion }}.zip
          retention-days: 1

  release:
    if: ${{ github.event.pull_request.title }} == "New Crowdin updates"
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download files
        uses: actions/download-artifact@v3
      - name: Release files
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ github.run_number }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          tag_name: pack_${{ github.run_number }}
          files: |
            */*.zip
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          method: squash
          repo: ${{ github.repository.full_name }}
