name: Build Pack

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.pull_request.title == 'New Crowdin updates' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        gameVersion: [1.19]
    runs-on: ubuntu-latest
    env:
      file_path: files/RPMTW-Translate-Resource-Pack-${{ matrix.gameVersion }}
    steps:
      - uses: actions/checkout@v3
      - name: Compressed the resource pack to a zip file
        uses: vimtor/action-zip@v1
        with:
          files: translated/zh_tw/source/zh_tw/${{ matrix.gameVersion }} meta/${{ matrix.gameVersion }} LICENSE
          dest: ${{ env.file_path }}.zip
      - name: Generate hash for the zip file (MD5)
        uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: md5
          file-name: ${{ env.file_path }}.md5
      - name: Generate hash for the zip file (SHA1)
        uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: sha1
          file-name: ${{ env.file_path }}.sha1
      - name: Generate hash for the zip file (SHA256)
        uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: sha256
          file-name: ${{ env.file_path }}.sha256
      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.gameVersion }}
          path: |
            ${{ env.file_path }}.zip
            ${{ env.file_path }}.md5
            ${{ env.file_path }}.sha1
            ${{ env.file_path }}.sha256
          retention-days: 1

  release:
    if: ${{ github.event.pull_request.title == 'New Crowdin updates' || github.event_name == 'workflow_dispatch' }}
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download files
        uses: actions/download-artifact@v3
      - name: Release files
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ github.run_number }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          tag_name: 1.0.${{ github.run_number }}
          files: |
            */*.zip
            */*.md5
            */*.sha1
            */*.sha256
      - name: Merge Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          method: squash
          repo: ${{ github.repository.full_name }}
