name: Download Mod

on:
  workflow_dispatch:
    inputs:
      gameVersion:
        description: "Game Version"
        type: choice
        options:
          - "1.16"
          - "1.17"
          - "1.18"
          - "1.19"
        required: true
      curseforgeProjectID:
        description: "CurseForge Project ID of the mod"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download files
        uses: RPMTW/Translation-Scripts@1.1.2
        with:
          action: "download_mod"
          args: ${{ github.event.inputs.curseforgeProjectID }}
          gameVersion: ${{ github.event.inputs.gameVersion }}

      - name: Move files
        run: |
          mkdir source
          mkdir source/zh_tw
          mv ${{ github.workspace }}/${{ github.event.inputs.gameVersion }} ${{ github.workspace }}/source/zh_tw/${{ github.event.inputs.gameVersion }}

      - name: Push changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: ${{ github.event.inputs.ref }}
          commit-message: Upload source files
          force-add: true
          files: ./source
          name: RPMTW Github Bot
          email: 41898282+github-actions[bot]@users.noreply.github.com
          rebase: true
